// Generated by LiveScript 1.5.0
var units, test, list;
units = {
  timetable: 'Timetable',
  options: 'Options',
  suggestions: 'Suggestions',
  stations: 'Stations'
};
require('livescript');
require('../register')({
  plugins: process.argv.length > 2
    ? []
    : ['istanbul']
});
test = require('tape');
list = process.argv.length > 2
  ? process.argv.slice(2)
  : Object.keys(units);
list.forEach(function(name){
  return test(units[name] || name, require("./" + name)['default']);
});
